[package]
name = "termilyon"
version = "0.1.2"
edition = "2024"

[dependencies]
gtk4 = "0.10"
vte4 = "0.9"
glib = "0.20"
gio = "0.20"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
directories = "5.0"
clap = { version = "4.5", features = ["derive"] }
